// DPRO CAR02 R41 – isolated domain service, NOT connected to production.
// Authentication and durable atomic DB transactions MUST be supplied by a verified adapter.
export class Car02Error extends Error { constructor(code,status=400){super(code);this.code=code;this.status=status;} }
const fail=(code,status)=>{throw new Car02Error(code,status)};
const states=['draft','pending','approved','declined','completed'];
const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
function validateActor(actor,shop,roles){
  if(!actor||actor.verified!==true||!actor.subject||!actor.shopCode||actor.shopCode!==shop||!roles.includes(actor.role)) fail('CAR02_UNAUTHORIZED',403);
}
function ensureItem(item){if(typeof item?.name!=='string'||!item.name.trim()||item.name.length>160||!Number.isSafeInteger(item?.price)||item.price<0||item.price>100_000_000)fail('CAR02_ITEM_INVALID',422)}
function money(items){items.forEach(ensureItem);const subtotal=items.reduce((s,i)=>s+i.price,0);if(!Number.isSafeInteger(subtotal)||subtotal>100_000_000)fail('CAR02_TOTAL_INVALID',422);const tax=Math.floor(subtotal*0.1);return{subtotal,tax,total:subtotal+tax}}
export function createCar02Service(db){
  if(!db||!['transaction','lookup','history'].every(k=>typeof db[k]==='function'))throw Error('CAR02_BACKEND_UNAVAILABLE');
  async function tx(actor,shop,key,fn,intent){validateActor(actor,shop,['owner','staff','customer']);if(typeof key!=='string'||key.length<12||key.length>150)fail('CAR02_IDEMPOTENCY_REQUIRED',422);return db.transaction({actor,shop,key,intent},fn)}
  return {
    async get({actor,shop,id}){validateActor(actor,shop,['owner','staff','customer']);if(!uuid(id))fail('CAR02_ID_INVALID',422);let o=await db.lookup(shop,id);if(!o)fail('CAR02_NOT_FOUND',404);if(actor.role==='customer'&&actor.customerId!==o.customerId)fail('CAR02_UNAUTHORIZED',403);return structuredClone(o)},
    async create({actor,shop,customerId,vehicleId,reservationId=null,key}){validateActor(actor,shop,['owner','staff']);if(!uuid(customerId)||!uuid(vehicleId)||(reservationId&&!uuid(reservationId)))fail('CAR02_REFERENCE_INVALID',422);return tx(actor,shop,key,async t=>{await t.assertLinks({shop,customerId,vehicleId,reservationId});return t.create({shop,customerId,vehicleId,reservationId,status:'draft',version:1,items:[],photos:[],events:[{type:'created',actor:actor.subject}]})},{op:'create',customerId,vehicleId,reservationId})},
    async report({actor,shop,id,observation,photos,key,expectedVersion}){validateActor(actor,shop,['owner','staff']);if(typeof observation!=='string'||!observation.trim()||observation.length>10000||!Array.isArray(photos)||photos.length>3||photos.some(p=>!uuid(p)))fail('CAR02_REPORT_INVALID',422);return tx(actor,shop,key,async t=>{let o=await t.getForUpdate(id);requireScope(o,shop,expectedVersion,'draft');await t.assertReadyPhotos({shop,order:o,ids:photos});o.observation=observation.trim();o.photos=[...photos];o.version++;o.events.push({type:'report_saved',actor:actor.subject});return t.save(o)},{op:'report',id,observation:observation.trim(),photos,expectedVersion})},
    async present({actor,shop,id,items,key,expectedVersion}){validateActor(actor,shop,['owner','staff']);if(!Array.isArray(items)||!items.length||items.length>30)fail('CAR02_ITEMS_INVALID',422);const totals=money(items);return tx(actor,shop,key,async t=>{let o=await t.getForUpdate(id);requireScope(o,shop,expectedVersion,'draft');if(!o.observation)fail('CAR02_REPORT_REQUIRED',409);const revision=(o.revision||0)+1;o.quote={revision,items:structuredClone(items),observation:o.observation,photos:[...o.photos],...totals,presentedAt:t.now()};o.revision=revision;o.status='pending';o.version++;o.events.push({type:'quote_presented',actor:actor.subject});return t.save(o)},{op:'present',id,items,expectedVersion})},
    async decide({actor,shop,id,decision,reason='',key,expectedVersion}){validateActor(actor,shop,['customer']);if(!['approved','declined'].includes(decision))fail('CAR02_DECISION_INVALID',422);if(decision==='declined'&&(!reason.trim()||reason.length>2000))fail('CAR02_REASON_REQUIRED',422);return tx(actor,shop,key,async t=>{let o=await t.getForUpdate(id);requireScope(o,shop,expectedVersion,'pending');if(o.customerId!==actor.customerId)fail('CAR02_UNAUTHORIZED',403);o.status=decision;o.version++;o.decision={value:decision,reason,subject:actor.subject,decidedAt:t.now(),revision:o.revision};o.events.push({type:`quote_${decision}`,actor:actor.subject});return t.save(o)},{op:'decide',id,decision,reason,expectedVersion})},
    async complete({actor,shop,id,key,expectedVersion}){validateActor(actor,shop,['owner','staff']);return tx(actor,shop,key,async t=>{let o=await t.getForUpdate(id);requireScope(o,shop,expectedVersion,'approved');if(o.decision?.revision!==o.quote?.revision)fail('CAR02_APPROVAL_MISMATCH',409);o.status='completed';o.version++;o.events.push({type:'completed',actor:actor.subject});return t.save(o)},{op:'complete',id,expectedVersion})},
    async history({actor,shop,id}){const o=await this.get({actor,shop,id});return structuredClone(o.events||[])},
  };
}
function requireScope(o,shop,version,status){if(!o||o.shop!==shop)fail('CAR02_NOT_FOUND',404);if(!Number.isSafeInteger(version)||version!==o.version)fail('CAR02_VERSION_CONFLICT',409);if(o.status!==status)fail('CAR02_STATE_CONFLICT',409)}
