import test from 'node:test';import assert from 'node:assert/strict';import {createCar02Service} from './car02-core.mjs';
const A='11111111-1111-4111-8111-111111111111', B='22222222-2222-4222-8222-222222222222', C='33333333-3333-4333-8333-333333333333';
let seq=0;function mock(){const rows=new Map(),ops=new Map();const db={lookup:async(s,id)=>rows.get(id)?.shop===s?rows.get(id):null,history:async()=>[],transaction:async({actor,shop,key},run)=>{let token=`${shop}:${actor.subject}:${key}`;if(ops.has(token))return structuredClone(ops.get(token));let t={assertLinks:async({customerId,vehicleId})=>{if(customerId!==A||vehicleId!==B)throw Error('mock scope mismatch')},create:async(o)=>{o.id=C;rows.set(o.id,o);return structuredClone(o)},getForUpdate:async id=>rows.get(id),assertReadyPhotos:async ({ids})=>{if(ids.length&&!ids.every(x=>x===B))throw Error('mock photo not ready')},now:()=>new Date('2026-10-10').toISOString(),save:async o=>{rows.set(o.id,o);return structuredClone(o)}};let v=await run(t);ops.set(token,structuredClone(v));return v}};return {svc:createCar02Service(db),rows}}
const staff={verified:true,role:'staff',shopCode:'S1',subject:'staff-1'},customer={verified:true,role:'customer',shopCode:'S1',subject:'line-1',customerId:A};
const q=n=>'test-key-000000'+n;
test('end-to-end draft → report → present → approve → complete; immutable result',async()=>{let {svc}=mock();let o=await svc.create({actor:staff,shop:'S1',customerId:A,vehicleId:B,key:q(1)});assert.equal(o.status,'draft');o=await svc.report({actor:staff,shop:'S1',id:C,observation:'点検済み',photos:[B],expectedVersion:o.version,key:q(2)});o=await svc.present({actor:staff,shop:'S1',id:C,items:[{name:'交換',price:101}],expectedVersion:o.version,key:q(3)});assert.equal(o.quote.total,111);o=await svc.decide({actor:customer,shop:'S1',id:C,decision:'approved',expectedVersion:o.version,key:q(4)});o=await svc.complete({actor:staff,shop:'S1',id:C,expectedVersion:o.version,key:q(5)});assert.equal(o.status,'completed');await assert.rejects(svc.report({actor:staff,shop:'S1',id:C,observation:'改竄',photos:[],key:q(6),expectedVersion:o.version}),/CAR02_STATE_CONFLICT/);assert.equal((await svc.history({actor:customer,shop:'S1',id:C})).length,5)});
test('unauthorized and cross-tenant blocked',async()=>{let {svc}=mock();await assert.rejects(svc.create({actor:{...staff,verified:false},shop:'S1',customerId:A,vehicleId:B,key:q(1)}),/CAR02_UNAUTHORIZED/);await assert.rejects(svc.create({actor:staff,shop:'S2',customerId:A,vehicleId:B,key:q(1)}),/CAR02_UNAUTHORIZED/)});
test('idempotency and stale version',async()=>{let {svc}=mock();let input={actor:staff,shop:'S1',customerId:A,vehicleId:B,key:q(1)};let a=await svc.create(input),b=await svc.create(input);assert.deepEqual(a,b);await assert.rejects(svc.report({actor:staff,shop:'S1',id:C,observation:'test',photos:[],expectedVersion:0,key:q(2)}),/CAR02_VERSION_CONFLICT/)});
test('customer ownership and quote validation',async()=>{let {svc}=mock();await svc.create({actor:staff,shop:'S1',customerId:A,vehicleId:B,key:q(1)});await assert.rejects(svc.get({actor:{...customer,customerId:B},shop:'S1',id:C}),/CAR02_UNAUTHORIZED/);await assert.rejects(svc.present({actor:staff,shop:'S1',id:C,items:[{name:'bad',price:-1}],expectedVersion:1,key:q(2)}),/CAR02_ITEM_INVALID/)});
test('cannot approve on behalf of customer',async()=>{let {svc}=mock();await assert.rejects(svc.decide({actor:staff,shop:'S1',id:C,decision:'approved',expectedVersion:1,key:q(1)}),/CAR02_UNAUTHORIZED/)});
